# This is a basic workflow to help you get started with Actions

name: My-Github_action
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask_deploy_ver_${{github.sha}}

on:
 push:
    branches: [ master ]
  
jobs:
  my_testing:
    runs-on: ubuntu-latest

    
    steps:
      - name: Print Hello Message in Testing
        run: echo "hello world from testing"
        
      - name: execute few commands
        run : |
          echo "Hello Message One"
          echo "Hello Message 2"
          echo "Appllication name: ${{env. APPLICATION_NAME}}"
      
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
      - name: Print Hello Message in deploy
        run: echo "hello world from deploy "
